-- RETIRED: do not run this file.
--
-- Access approval, approved-member RLS, Cairn Close, reciprocal partner privacy,
-- and private nudges now live in the consolidated migration:
--
--   cairn-product-upgrade.sql
--
-- The former access-hub migration could approve pending users when rerun and is
-- intentionally no longer executable.
